In [1]:
import pandas as pd

In [2]:
matches=pd.read_csv("football_data.csv",index_col=0)

In [3]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,...,Match Report,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,Match Report,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,Match Report,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,Match Report,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,Match Report,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,L,0.0,4.0,Tottenham,...,Match Report,NaN,8.0,1.0,17.4,0.0,0.0,0.0,2021,Sheffield United
39,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,L,0.0,2.0,Crystal Palace,...,Match Report,NaN,7.0,0.0,11.4,1.0,0.0,0.0,2021,Sheffield United
40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,W,1.0,0.0,Everton,...,Match Report,NaN,10.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United
41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,L,0.0,1.0,Newcastle Utd,...,Match Report,NaN,11.0,1.0,16.0,1.0,0.0,0.0,2021,Sheffield United
42,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,1.0,0.0,Burnley,...,Match Report,NaN,12.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United

In [4]:
matches['date']=pd.to_datetime(matches['date'])
matches['venue_code']=matches['venue'].astype('category').cat.codes
matches['opp_code']=matches['opponent'].astype('category').cat.codes
matches['hour']=matches['time'].str.replace(":.+","",regex=True).astype('int')
matches['day_code']=matches['date'].dt.dayofweek

In [5]:
matches["target"]=(matches['result']=='W').astype('int')

In [6]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,...,1.0,0.0,0.0,2022,Manchester City,0,18,16,6,0
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,1.0,0.0,0.0,2022,Manchester City,1,15,15,5,1
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,0.0,0.0,0.0,2022,Manchester City,1,0,12,5,1
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,0.0,0.0,0.0,2022,Manchester City,0,10,15,5,1
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,1.0,0.0,0.0,2022,Manchester City,1,17,15,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,L,0.0,4.0,Tottenham,...,0.0,0.0,0.0,2021,Sheffield United,0,18,19,6,0
39,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,L,0.0,2.0,Crystal Palace,...,1.0,0.0,0.0,2021,Sheffield United,1,6,15,5,0
40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,W,1.0,0.0,Everton,...,0.0,0.0,0.0,2021,Sheffield United,0,7,19,6,1
41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,L,0.0,1.0,Newcastle Utd,...,1.0,0.0,0.0,2021,Sheffield United,0,14,18,2,0
42,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,1.0,0.0,Burnley,...,0.0,0.0,0.0,2021,Sheffield United,1,4,16,6,1

#### Training

In [46]:
from sklearn.ensemble import RandomForestClassifier

In [48]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [9]:
train = matches[matches["date"]<'2022-01-01']

In [10]:
test=matches[matches['date']>'2022-01-01']

In [49]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [50]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [51]:
preds = rf.predict(test[predictors])

In [14]:
from sklearn.metrics import accuracy_score

In [53]:
acc= accuracy_score(test["target"], preds)
error = accuracy_score(test["target"], preds)

In [56]:
error

0.6123188405797102

In [57]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))

In [45]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted    0
actual
0          172
1          104

In [60]:
from sklearn.metrics import precision_score

precision_score(test["target"], preds)

0.4745762711864407

In [61]:
grouped_matches =matches.groupby('team')

In [62]:
group=grouped_matches.get_group('Arsenal')

In [63]:
group

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
0,2021-08-13,20:00,Premier League,Matchweek 1,Fri,Away,L,0.0,2.0,Brentford,...,1.0,0.0,0.0,2022,Arsenal,0,2,20,4,0
1,2021-08-22,16:30,Premier League,Matchweek 2,Sun,Home,L,0.0,2.0,Chelsea,...,0.0,0.0,0.0,2022,Arsenal,1,5,16,6,0
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Away,L,0.0,5.0,Manchester City,...,0.0,0.0,0.0,2022,Arsenal,0,12,12,5,0
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Home,W,1.0,0.0,Norwich City,...,1.0,0.0,0.0,2022,Arsenal,1,15,15,5,1
5,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Away,W,1.0,0.0,Burnley,...,1.0,0.0,0.0,2022,Arsenal,0,4,15,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,2021-05-02,14:00,Premier League,Matchweek 34,Sun,Away,W,2.0,0.0,Newcastle Utd,...,1.0,0.0,0.0,2021,Arsenal,0,14,14,6,1
54,2021-05-09,19:00,Premier League,Matchweek 35,Sun,Home,W,3.0,1.0,West Brom,...,1.0,0.0,0.0,2021,Arsenal,1,20,19,6,1
55,2021-05-12,20:15,Premier League,Matchweek 36,Wed,Away,W,1.0,0.0,Chelsea,...,0.0,0.0,0.0,2021,Arsenal,0,5,20,2,1
56,2021-05-19,19:00,Premier League,Matchweek 37,Wed,Away,W,3.0,1.0,Crystal Palace,...,0.0,0.0,0.0,2021,Arsenal,0,6,19,2,1
57,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,2.0,0.0,Brighton,...,1.0,0.0,0.0,2021,Arsenal,1,3,16,6,1

In [78]:
def rolling_average(group, cols, new_cols):
    group=group.sort_values('date')
    rolling_start=group[cols].rolling(3,closed='left').mean()
    group[new_cols]=rolling_start
    group= group.dropna(subset=new_cols)
    return group

In [148]:
def rolling_wins(group, col, new_col):
    group=group.sort_values('date')
    rolling_start=group[col].rolling(3,closed='left').sum()
    group[new_col]=rolling_start
    group= group.dropna(subset=new_col)
    return group

In [149]:
cols=['gf','ga','sh','sot','dist','fk','pk','pkatt']
col=['target']
new_cols=[f"{stat}_rolling" for stat in cols]
new_col=['target_sum']

In [150]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [175]:
rolling_average(group,cols,new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
6,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2.0,1.0,Sheffield Utd,...,6,1,2.000000,1.333333,7.666667,3.666667,14.733333,0.666667,0.000000,0.000000
7,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0.0,1.0,Manchester City,...,5,0,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000,0.000000
9,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0.0,1.0,Leicester City,...,6,0,1.000000,1.666667,7.000000,3.666667,16.733333,0.666667,0.000000,0.000000
11,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1.0,0.0,Manchester Utd,...,6,1,0.666667,1.000000,9.666667,4.000000,16.033333,1.000000,0.000000,0.000000
13,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0.0,3.0,Aston Villa,...,6,0,0.333333,0.666667,9.666667,2.666667,18.033333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35,2022-04-04,20:00,Premier League,Matchweek 31,Mon,Away,L,0.0,3.0,Crystal Palace,...,0,0,1.000000,0.666667,13.000000,3.666667,18.400000,0.000000,0.333333,0.333333
36,2022-04-09,15:00,Premier League,Matchweek 32,Sat,Home,L,1.0,2.0,Brighton,...,5,0,0.333333,1.666667,10.333333,2.666667,19.300000,0.000000,0.000000,0.000000
37,2022-04-16,15:00,Premier League,Matchweek 33,Sat,Away,L,0.0,1.0,Southampton,...,5,0,0.666667,1.666667,14.000000,3.333333,17.566667,0.666667,0.000000,0.000000
38,2022-04-20,19:45,Premier League,Matchweek 25,Wed,Away,W,4.0,2.0,Chelsea,...,2,1,0.333333,2.000000,18.333333,4.333333,17.400000,1.000000,0.000000,0.000000
39,2022-04-23,12:30,Premier League,Matchweek 34,Sat,Home,W,3.0,1.0,Manchester Utd,...,5,1,1.666667,1.666667,18.666667,4.333333,17.900000,1.000000,0.333333,0.333333

In [176]:
matches_rolling=matches.groupby('team').apply(lambda x:rolling_average(x,cols, new_cols))

In [177]:
matches_rolling.tail()

                                 date   time            comp         round  \
team
Wolverhampton Wanderers 32 2022-03-13  14:00  Premier League  Matchweek 29
                        33 2022-03-18  20:00  Premier League  Matchweek 30
                        34 2022-04-02  15:00  Premier League  Matchweek 31
                        35 2022-04-08  20:00  Premier League  Matchweek 32
                        36 2022-04-24  14:00  Premier League  Matchweek 34

                            day venue result   gf   ga       opponent  ...  \
team                                                                   ...
Wolverhampton Wanderers 32  Sun  Away      W  1.0  0.0        Everton  ...
                        33  Fri  Home      L  2.0  3.0   Leeds United  ...
                        34  Sat  Home      W  2.0  1.0    Aston Villa  ...
                        35  Fri  Away      L  0.0  1.0  Newcastle Utd  ...
                        36  Sun  Away      L  0.0  1.0        Burnley  ...

                            day_code  target  gf_rolling  ga_rolling  \
team
Wolverhampton Wanderers 32         6       1    1.333333    1.000000
                        33         4       0    1.666667    0.666667
                        34         5       1    2.333333    1.000000
                        35         4       0    1.666667    1.333333
                        36         6       0    1.333333    1.666667

                           sh_rolling sot_rolling dist_rolling fk_rolling  \
team
Wolverhampton Wanderers 32  12.333333    3.666667    19.300000        0.0
                        33  12.333333    4.333333    19.600000        0.0
                        34  13.000000    5.333333    19.833333        0.0
                        35  13.000000    5.000000    18.533333        0.0
                        36  10.000000    4.666667    17.633333        0.0

                            pk_rolling  pkatt_rolling
team
Wolverhampton Wanderers 32         0.0            0.0
                        33         0.0            0.0
                        34         0.0            0.0
                        35         0.0            0.0
                        36         0.0            0.0

[5 rows x 40 columns]

In [178]:
matches_rolling=matches_rolling.droplevel('team')

In [179]:
matches_rolling.index=range(matches_rolling.shape[0])
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2.0,1.0,Sheffield Utd,...,6,1,2.000000,1.333333,7.666667,3.666667,14.733333,0.666667,0.000000,0.000000
1,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0.0,1.0,Manchester City,...,5,0,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000,0.000000
2,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0.0,1.0,Leicester City,...,6,0,1.000000,1.666667,7.000000,3.666667,16.733333,0.666667,0.000000,0.000000
3,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1.0,0.0,Manchester Utd,...,6,1,0.666667,1.000000,9.666667,4.000000,16.033333,1.000000,0.000000,0.000000
4,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0.0,3.0,Aston Villa,...,6,0,0.333333,0.666667,9.666667,2.666667,18.033333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1312,2022-03-13,14:00,Premier League,Matchweek 29,Sun,Away,W,1.0,0.0,Everton,...,6,1,1.333333,1.000000,12.333333,3.666667,19.300000,0.000000,0.000000,0.000000
1313,2022-03-18,20:00,Premier League,Matchweek 30,Fri,Home,L,2.0,3.0,Leeds United,...,4,0,1.666667,0.666667,12.333333,4.333333,19.600000,0.000000,0.000000,0.000000
1314,2022-04-02,15:00,Premier League,Matchweek 31,Sat,Home,W,2.0,1.0,Aston Villa,...,5,1,2.333333,1.000000,13.000000,5.333333,19.833333,0.000000,0.000000,0.000000
1315,2022-04-08,20:00,Premier League,Matchweek 32,Fri,Away,L,0.0,1.0,Newcastle Utd,...,4,0,1.666667,1.333333,13.000000,5.000000,18.533333,0.000000,0.000000,0.000000
1316,2022-04-24,14:00,Premier League,Matchweek 34,Sun,Away,L,0.0,1.0,Burnley,...,6,0,1.333333,1.666667,10.000000,4.666667,17.633333,0.000000,0.000000,0.000000

In [180]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2022-01-01']
    test = data[data["date"] > '2022-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    return combined, error

In [181]:
combined, error = make_predictions(matches_rolling, predictors + new_cols)

In [182]:
error

0.625

In [101]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [102]:
combined.head()

    actual  predicted       date     team   opponent result
55       0          0 2022-01-23  Arsenal    Burnley      D
56       1          0 2022-02-10  Arsenal     Wolves      W
57       1          0 2022-02-19  Arsenal  Brentford      W
58       1          1 2022-02-24  Arsenal     Wolves      W
59       1          1 2022-03-06  Arsenal    Watford      W

In [136]:
class MissingDict(dict):
    __missing__ = lambda self, key: key
map_values={
    "Brighton and Hove Albion": "Brighton",
    "Manchester United": "Manchester Utd", 
    "Newcastle United": "Newcastle Utd",
    "Tottenham Hotspur":"Tottenham",
    "West Ham United":"West Ham",
    "Wolverhampton Wanderers":"Wolves"
}
mapping = MissingDict(**map_values)

In [130]:
mapping['Tottenham']

'Shit'

In [131]:
combined["new_team"]=combined["team"].map(mapping)

In [132]:
combined

,actual,predicted,date,team,opponent,result,new_team
55,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal
56,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal
57,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal
58,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal
59,1,1,2022-03-06,Arsenal,Watford,W,Arsenal
...,...,...,...,...,...,...,...
1312,1,0,2022-03-13,Wolverhampton Wanderers,Everton,W,Wolves
1313,0,0,2022-03-18,Wolverhampton Wanderers,Leeds United,L,Wolves
1314,1,0,2022-04-02,Wolverhampton Wanderers,Aston Villa,W,Wolves
1315,0,0,2022-04-08,Wolverhampton Wanderers,Newcastle Utd,L,Wolves
1316,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L,Wolves

In [133]:
merged=combined.merge(combined, left_on=["date","new_team"],right_on=["date","opponent"])

In [134]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
1,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
2,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
3,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
4,1,1,2022-03-06,Arsenal,Watford,W,Arsenal,0,0,Watford,Arsenal,L,Watford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,1,0,2022-03-13,Wolverhampton Wanderers,Everton,W,Wolves,0,0,Everton,Wolves,L,Everton
258,0,0,2022-03-18,Wolverhampton Wanderers,Leeds United,L,Wolves,1,0,Leeds United,Wolves,W,Leeds United
259,1,0,2022-04-02,Wolverhampton Wanderers,Aston Villa,W,Wolves,0,0,Aston Villa,Wolves,L,Aston Villa
260,0,0,2022-04-08,Wolverhampton Wanderers,Newcastle Utd,L,Wolves,1,0,Newcastle United,Wolves,W,Newcastle Utd
261,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L,Wolves,1,0,Burnley,Wolves,W,Burnley

In [135]:
merged[(merged["predicted_x"]==1)&(merged['predicted_y']==0)]["actual_x"].value_counts()

actual_x
1    27
0    13
Name: count, dtype: int64